# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 54be84039a1e6f0e9848618c38043677b07ccfb468d78128be8c62c4e3e02bfa31242b31a9dc77d946068260fa47ab9abcc4d09821de2fe801a691b6e5a02146

test:
  secret_key_base: 3dd21c52ff7711016cfc6ba8edbac709eeab5ed9029014a278ba9e245a690fd6d9fcc2e55cee65dbafbcdd3653e6615af570cf06c8d6670854e67bf420b2d63d

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
